In [1]:
#Data structures and control structures 
#list operations
# Create a list of 5 integers
numbers = [10, 20, 30, 40, 50]
print("Original List:", numbers)

# append() - adds element at the end
numbers.append(60)
print("After append:", numbers)

# extend() - adds multiple elements
numbers.extend([70, 80])
print("After extend:", numbers)

# insert() - insert element at specific position
numbers.insert(2, 25)
print("After insert:", numbers)

# remove() - removes specific value
numbers.remove(30)
print("After remove:", numbers)

# pop() - removes element by index (default last)
popped = numbers.pop()
print("Popped element:", popped)
print("After pop:", numbers)

# index() - find index of value
index_val = numbers.index(40)
print("Index of 40:", index_val)

# count() - count occurrences
numbers.append(20)
count_val = numbers.count(20)
print("Count of 20:", count_val)

# sort() - sorts list
numbers.sort()
print("Sorted list:", numbers)

# reverse() - reverses list
numbers.reverse()
print("Reversed list:", numbers)

# clear() - removes all elements
numbers.clear()
print("After clear:", numbers)

Original List: [10, 20, 30, 40, 50]
After append: [10, 20, 30, 40, 50, 60]
After extend: [10, 20, 30, 40, 50, 60, 70, 80]
After insert: [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove: [10, 20, 25, 40, 50, 60, 70, 80]
Popped element: 80
After pop: [10, 20, 25, 40, 50, 60, 70]
Index of 40: 3
Count of 20: 2
Sorted list: [10, 20, 20, 25, 40, 50, 60, 70]
Reversed list: [70, 60, 50, 40, 25, 20, 20, 10]
After clear: []


In [2]:
#Tuple modification
# Create a tuple with 3 student names
students = ("Alice", "Bob", "Charlie")
print("Original Tuple:", students)

# Try changing the second name
students[1] = "David"

Original Tuple: ('Alice', 'Bob', 'Charlie')


TypeError: 'tuple' object does not support item assignment

In [3]:
#this cant able to change because A tuple is an immutable data structure

In [4]:
#set with duplicate values
# Create a set with duplicate integers
numbers_set = {1, 2, 3, 4, 4, 5, 5, 6}

print("Set values:", numbers_set)

Set values: {1, 2, 3, 4, 5, 6}


In [5]:
#A set is a collection of unique elements.

In [6]:
# Create dictionary
person = {
    "name": "John",
    "age": 25,
    "city": "Bangalore"
}

print("Original Dictionary:", person)

# Update age
person["age"] = 26

# Add new key
person["email"] = "john@email.com"

print("Updated Dictionary:", person)

Original Dictionary: {'name': 'John', 'age': 25, 'city': 'Bangalore'}
Updated Dictionary: {'name': 'John', 'age': 26, 'city': 'Bangalore', 'email': 'john@email.com'}


In [7]:
#Votting Eligibility
# Age variable
age = 20

# Check voting eligibility
if age >= 18:
    print("The person is eligible to vote.")
else:
    print("The person is not eligible to vote.")

The person is eligible to vote.


In [9]:
#Grade calculator
# Marks variable
marks = 95

if marks >= 90:
    grade = 'A'
elif marks >= 75:
    grade = 'B'
elif marks >= 50:
    grade = 'C'
else:
    grade = 'Fail'

print("Grade:", grade)

Grade: A


In [10]:
#positive and even number check
# Given number
num = 8

if num > 0:
    print("The number is positive.")
    
    if num % 2 == 0:
        print("The number is also even.")
    else:
        print("The number is odd.")

elif num == 0:
    print("The number is zero.")

else:
    print("The number is negative.")

The number is positive.
The number is also even.


In [11]:
#SECTION B:NumPy
# Import required libraries
import numpy as np
import pandas as pd

In [12]:
#creating different NumPy Arrays
# Scalar using numpy
scalar = np.array(5)
print("Scalar:", scalar)

# 1D array with values from 1 to 5
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)

# 2D array (2x3) with values from 10 to 60 in steps of 10
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60]])

print("2D Array:\n", array_2d)

Scalar: 5
1D Array: [1 2 3 4 5]
2D Array:
 [[10 20 30]
 [40 50 60]]


In [13]:
#Generate a 4*4 Random integer array
# Generate 4x4 array of random integers between 0 and 100
random_array = np.random.randint(0, 101, size=(4,4))

print("4x4 Random Array:\n", random_array)

4x4 Random Array:
 [[35 46 98 13]
 [89 64  5 28]
 [98 67 20 69]
 [86 54  4 48]]


In [14]:
#Convert NumPy array to pandas data frame
# Create a 3x3 numpy array
array_2d = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])

print("Numpy Array:\n", array_2d)

# Convert numpy array to pandas DataFrame
df = pd.DataFrame(array_2d, columns=['A','B','C'])

print("\nDataFrame:\n", df)

Numpy Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

DataFrame:
    A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [15]:
#Exploring Pandas
# Create a dictionary with sample data
data = {
    'Name': ['Alice','Bob','Charlie','David','Eva','Frank','Grace','Helen','Ivy','Jack'],
    'Age': [25,30,35,40,28,33,29,31,26,38],
    'City': ['New York','London','Paris','Tokyo','Berlin','Rome','Madrid','Sydney','Dubai','Toronto'],
    'Salary': [50000,60000,55000,None,52000,58000,60000,None,54000,62000]
}

# Create DataFrame
df = pd.DataFrame(data)

print("Original DataFrame:\n")
print(df)

Original DataFrame:

      Name  Age      City   Salary
0    Alice   25  New York  50000.0
1      Bob   30    London  60000.0
2  Charlie   35     Paris  55000.0
3    David   40     Tokyo      NaN
4      Eva   28    Berlin  52000.0
5    Frank   33      Rome  58000.0
6    Grace   29    Madrid  60000.0
7    Helen   31    Sydney      NaN
8      Ivy   26     Dubai  54000.0
9     Jack   38   Toronto  62000.0


In [16]:
#Use .info() and .describe()
# Display basic information about DataFrame
print("\nDataFrame Info:\n")
df.info()

# Display statistical summary
print("\nStatistical Description:\n")
print(df.describe())


DataFrame Info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

Statistical Description:

             Age        Salary
count  10.000000      8.000000
mean   31.500000  56375.000000
std     4.972145   4274.091382
min    25.000000  50000.000000
25%    28.250000  53500.000000
50%    30.500000  56500.000000
75%    34.500000  60000.000000
max    40.000000  62000.000000


In [17]:
#Select 'Name' and 'City' columns
selected_columns = df[['Name','City']]

print("\nSelected Columns:\n")
print(selected_columns)


Selected Columns:

      Name      City
0    Alice  New York
1      Bob    London
2  Charlie     Paris
3    David     Tokyo
4      Eva    Berlin
5    Frank      Rome
6    Grace    Madrid
7    Helen    Sydney
8      Ivy     Dubai
9     Jack   Toronto


In [18]:
#Drop 'city' column
df = df.drop('City', axis=1)

print("\nDataFrame after dropping City column:\n")
print(df)


DataFrame after dropping City column:

      Name  Age   Salary
0    Alice   25  50000.0
1      Bob   30  60000.0
2  Charlie   35  55000.0
3    David   40      NaN
4      Eva   28  52000.0
5    Frank   33  58000.0
6    Grace   29  60000.0
7    Helen   31      NaN
8      Ivy   26  54000.0
9     Jack   38  62000.0


In [19]:
#Fill missing values in Salary column with mean
# Calculate mean salary
mean_salary = df['Salary'].mean()

# Fill missing values
df['Salary'] = df['Salary'].fillna(mean_salary)

print("\nDataFrame after filling missing Salary values:\n")
print(df)


DataFrame after filling missing Salary values:

      Name  Age   Salary
0    Alice   25  50000.0
1      Bob   30  60000.0
2  Charlie   35  55000.0
3    David   40  56375.0
4      Eva   28  52000.0
5    Frank   33  58000.0
6    Grace   29  60000.0
7    Helen   31  56375.0
8      Ivy   26  54000.0
9     Jack   38  62000.0


In [20]:
#Remove duplicate rows
df = df.drop_duplicates()

print("\nDataFrame after removing duplicates:\n")
print(df)


DataFrame after removing duplicates:

      Name  Age   Salary
0    Alice   25  50000.0
1      Bob   30  60000.0
2  Charlie   35  55000.0
3    David   40  56375.0
4      Eva   28  52000.0
5    Frank   33  58000.0
6    Grace   29  60000.0
7    Helen   31  56375.0
8      Ivy   26  54000.0
9     Jack   38  62000.0
